"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = "$all"

# Change the default prompt characters
[character]
success_symbol = "[❯](green)"
error_symbol = "[⨯](red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only_style = "197"
read_only = "  "
format = "@ [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "↨ "
format = "on [$symbol$branch]($style) "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "${count}R "
deleted = "${count}D "
modified = "${count}M "
untracked = "${count}A "

[dotnet]
disabled = false

[username]
style_user = "243"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
disabled = false
